

export const categories = [
  { id: 1, name: 'All', icon: '🛒' },
  { id: 2, name: 'Electronics', icon: '📱' },
  { id: 3, name: 'Clothing', icon: '👕' },
  { id: 4, name: 'Home & Kitchen', icon: '🏠' },
  { id: 5, name: 'Books', icon: '📚' },
  { id: 6, name: 'Sports', icon: '⚽' },
];

export const products = [
  {
    id: 1,
    name: 'Wireless Bluetooth Headphones',
    description: 'High-quality wireless headphones with noise cancellation and 30-hour battery life.',
    price: 99.99,
    category: 'Electronics',
    image: '/images/products/headphones.jpg',
    stock: 50,
    rating: 4.5,
    reviews: 128,
  },
  {
    id: 2,
    name: 'Classic Cotton T-Shirt',
    description: 'Comfortable 100% cotton t-shirt available in multiple colors.',
    price: 19.99,
    category: 'Clothing',
    image: '/images/products/tshirt.jpg',
    stock: 100,
    rating: 4.2,
    reviews: 56,
  },
  {
    id: 3,
    name: 'Smart Watch Series 5',
    description: 'Advanced smartwatch with fitness tracking and heart rate monitor.',
    price: 249.99,
    category: 'Electronics',
    image: '/images/products/smartwatch.jpg',
    stock: 30,
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 4,
    name: 'Ceramic Coffee Mug Set',
    description: 'Set of 4 ceramic mugs with elegant design, microwave safe.',
    price: 34.99,
    category: 'Home & Kitchen',
    image: '/images/products/mug.jpg',
    stock: 75,
    rating: 4.3,
    reviews: 42,
  },
  {
    id: 5,
    name: 'JavaScript: The Definitive Guide',
    description: 'Comprehensive guide to JavaScript programming, 7th edition.',
    price: 49.99,
    category: 'Books',
    image: '/images/products/book.jpg',
    stock: 40,
    rating: 4.8,
    reviews: 203,
  },
  {
    id: 6,
    name: 'Yoga Mat Premium',
    description: 'Non-slip yoga mat with carrying strap, 6mm thickness.',
    price: 29.99,
    category: 'Sports',
    image: '/images/products/yogamat.jpg',
    stock: 60,
    rating: 4.4,
    reviews: 67,
  },
  {
    id: 7,
    name: 'Laptop Backpack',
    description: 'Water-resistant backpack with laptop compartment and USB port.',
    price: 59.99,
    category: 'Electronics',
    image: '/images/products/backpack.jpg',
    stock: 45,
    rating: 4.6,
    reviews: 94,
  },
  {
    id: 8,
    name: 'Stainless Steel Water Bottle',
    description: '1L insulated water bottle, keeps drinks cold for 24 hours.',
    price: 24.99,
    category: 'Sports',
    image: '/images/products/bottle.jpg',
    stock: 80,
    rating: 4.5,
    reviews: 121,
  },
];

export const featuredProducts = products.slice(0, 4); 